<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FluidProcessor\FluidProcessor.csproj" />
    <ProjectReference Include="..\LiquidProcessor.Core\LiquidProcessor.Core.csproj" />
    <ProjectReference Include="..\LiquidProcessor\DotLiquidProcessor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotLiquid" Version="2.2.595" />
    <PackageReference Include="Fluid.Core" Version="2.10.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Parlot" Version="0.0.25" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="TimeZoneConverter" Version="6.1.0" />
  </ItemGroup>
</Project>